export const USERS_RETRIEVER = 'USERS-RETRIEVER';
export const ROLES_RETRIEVER = 'ROLES-RETRIEVER';

export const USERS_REPOSITORY = 'USERS-REPOSITORY';
export const ROLES_REPOSITORY = 'ROLES-REPOSITORY';

export const PASSWORD_HASHER = 'PASSWORD-HASHER';
