global:
  componentMetaConfig:
    library:
      name: library
      collection: libraries
      classTypeName: LibraryComponent

    library.book:
      name: book
      collection: books
      classTypeName: BookComponent

    book.authors:
      name: authors
      collection: authors
      classTypeName: AuthorComponent

    library.member:
      name: member
      collection: members
      classTypeName: MemberComponent

    library.loan:
      name: loan
      collection: loans
      classTypeName: LoanComponent
